navbar-links:
    Archive: /archives
    GitHub: https://github.com/wololock/wololock.github.io
    YouTube: /youtube

avatar: /hexo.png
favicon: /hexo.png

index_cover: /img/post-bg-1.jpg

header:
  title: Szymon Stępniak
  motto: I walk through e.printStackTrace() so you don't have to

rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
  - "Noto+Serif:400,700,400italic"
  - "Source+Code+Pro"
  - "Droid+Sans+Mono:400,700"

highlight:
  enable: true
  style_path: "/css/highlight.css"

footer:
  rss:
    link: https://feeds.feedburner.com/Eprintstacktracenet
    title: RSS
    icon: fa-rss
    enable: true
  twitter:
    link: https://twitter.com/wololock
    title: Twitter
    icon: fa-twitter
    enable: true
  github:
    link: https://github.com/wololock
    title: GitHub
    icon: fa-github
    enable: true
  stackoverflow:
    link: https://stackoverflow.com/users/2194470/szymon-stepniak?tab=profile
    title: StackOverflow
    icon: fa-stack-overflow
    enable: false
  youtube:
    link: https://www.youtube.com/c/eprintstacktrace
    title: YouTube
    icon: fa-youtube
    enable: true
  mail:
    link: 'mailto:szymon.stepniak@gmail.com'
    title: Email me
    icon: fa-envelope
    enable: true
  linkedin:
    link: https://www.linkedin.com/in/szymon-stępniak-9a0b1630
    title: LinkedIn
    icon: fa-linkedin
    enable: false
  keybase:
    link: https://keybase.io/wololock
    title: Keybase
    icon: fa-user-secret
    enable: true

google_analytics: UA-42400890-5

comment:
  enable: disqus
  id: eprintstacktrace

